# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

W_ties <- function(x, y, k) {
    .Call('testforDEP_W_ties', PACKAGE = 'testforDEP', x, y, k)
}

W_no_ties <- function(x, y, k) {
    .Call('testforDEP_W_no_ties', PACKAGE = 'testforDEP', x, y, k)
}

MC_p <- function(x, y, W, sn, k) {
    .Call('testforDEP_MC_p', PACKAGE = 'testforDEP', x, y, W, sn, k)
}

Tn <- function(x, y) {
    .Call('testforDEP_Tn', PACKAGE = 'testforDEP', x, y)
}

MC_EL_count <- function(tn, n, sn) {
    .Call('testforDEP_MC_EL_count', PACKAGE = 'testforDEP', tn, n, sn)
}

randEl <- function(n, sn) {
    .Call('testforDEP_randEl', PACKAGE = 'testforDEP', n, sn)
}

emcdf_output <- function(x, y, is_tie) {
    .Call('testforDEP_emcdf_output', PACKAGE = 'testforDEP', x, y, is_tie)
}

SortByX <- function(x, y) {
    .Call('testforDEP_SortByX', PACKAGE = 'testforDEP', x, y)
}

vex <- function(x, y) {
    .Call('testforDEP_vex', PACKAGE = 'testforDEP', x, y)
}

MC_count <- function(Ts, n, sn) {
    .Call('testforDEP_MC_count', PACKAGE = 'testforDEP', Ts, n, sn)
}

randTs <- function(n, sn) {
    .Call('testforDEP_randTs', PACKAGE = 'testforDEP', n, sn)
}

